CREATE OR ALTER     PROCEDURE LOAD_CLEAN_INV1
AS
BEGIN
    SET NOCOUNT ON;

    ----------------------------------------------------------------------
    -- 0) Leer el LastWatermark desde ETL.Watermarks (compartido con OINV)
    ----------------------------------------------------------------------
    DECLARE @LastWatermark DATETIME2(6);

    SELECT 
        @LastWatermark = w.LastWatermark
    FROM ETL.Watermarks AS w
   WHERE w.PipelineName = 'OINV';   -- mismo watermark que usa OINV

    -- Si por alguna razón no hay watermark, ponemos uno muy antiguo
    IF @LastWatermark IS NULL
        SET @LastWatermark = '2025-01-01';   -- ajústalo si quieres otra fecha base

    ----------------------------------------------------------------------
    -- 1) Tomar SOLO encabezados cambiados desde el watermark,
    --    PERO desde CLEAN_OINV (ya sin duplicados por DocEntry)
    ----------------------------------------------------------------------
    IF OBJECT_ID('tempdb..#OINV_CHANGED') IS NOT NULL DROP TABLE #OINV_CHANGED;

    SELECT 
        c.DocEntry,
        c.RowLastChange
    INTO #OINV_CHANGED
    FROM SBO_NMU_PROD.CLEAN_OINV AS c
    WHERE c.RowLastChange > @LastWatermark;   -- solo facturas que cambiaron

    -- Si no hay facturas cambiadas, no hay nada que hacer
    IF NOT EXISTS (SELECT 1 FROM #OINV_CHANGED)
        RETURN;

    

    ----------------------------------------------------------------------
    -- 3) Borrar de CLEAN_INV1 solo las líneas de esas facturas
    ----------------------------------------------------------------------
    DELETE tgt
    FROM SBO_NMU_PROD.CLEAN_INV1 AS tgt
    INNER JOIN #OINV_CHANGED AS c
        ON c.DocEntry = tgt.DocEntry;

    ----------------------------------------------------------------------
    -- 4) Insertar nuevamente las líneas actualizadas (sin duplicados)
    --    IMPORTANTE: lista de columnas explícita para no incluir rn
    ----------------------------------------------------------------------
    ----------------------------------------------------------------------
    -- 2) Deduplicar INV1 por (DocEntry, LineNum) usando ROW_NUMBER
    ----------------------------------------------------------------------
    ;WITH INV1_RN AS
    (
        SELECT 
            i.*,
            ROW_NUMBER() OVER (
                PARTITION BY i.DocEntry, i.LineNum
                ORDER BY i.DocEntry, i.LineNum
            ) AS rn
        FROM SBO_NMU_PROD.INV1 AS i
        INNER JOIN #OINV_CHANGED AS c
            ON c.DocEntry = i.DocEntry
    )
    INSERT INTO SBO_NMU_PROD.CLEAN_INV1
    (
         DocEntry
        ,LineNum
        ,TargetType
        ,TrgetEntry
        ,BaseRef
        ,BaseType
        ,BaseEntry
        ,BaseLine
        ,LineStatus
        ,ItemCode
        ,Dscription
        ,Quantity
        ,ShipDate
        ,OpenQty
        ,Price
        ,Currency
        ,Rate
        ,DiscPrcnt
        ,LineTotal
        ,TotalFrgn
        ,OpenSum
        ,OpenSumFC
        ,VendorNum
        ,SerialNum
        ,WhsCode
        ,SlpCode
        ,Commission
        ,TreeType
        ,AcctCode
        ,TaxStatus
        ,GrossBuyPr
        ,PriceBefDi
        ,DocDate
        ,Flags
        ,OpenCreQty
        ,UseBaseUn
        ,SubCatNum
        ,BaseCard
        ,TotalSumSy
        ,OpenSumSys
        ,InvntSttus
        ,OcrCode
        ,Project
        ,CodeBars
        ,VatPrcnt
        ,VatGroup
        ,PriceAfVAT
        ,Height1
        ,Hght1Unit
        ,Height2
        ,Hght2Unit
        ,Width1
        ,Wdth1Unit
        ,Width2
        ,Wdth2Unit
        ,Length1
        ,Len1Unit
        ,length2
        ,Len2Unit
        ,Volume
        ,VolUnit
        ,Weight1
        ,Wght1Unit
        ,Weight2
        ,Wght2Unit
        ,Factor1
        ,Factor2
        ,Factor3
        ,Factor4
        ,PackQty
        ,UpdInvntry
        ,BaseDocNum
        ,BaseAtCard
        ,SWW
        ,VatSum
        ,VatSumFrgn
        ,VatSumSy
        ,FinncPriod
        ,ObjType
        ,LogInstanc
        ,BlockNum
        ,ImportLog
        ,DedVatSum
        ,DedVatSumF
        ,DedVatSumS
        ,IsAqcuistn
        ,DistribSum
        ,DstrbSumFC
        ,DstrbSumSC
        ,GrssProfit
        ,GrssProfSC
        ,GrssProfFC
        ,VisOrder
        ,INMPrice
        ,PoTrgNum
        ,PoTrgEntry
        ,DropShip
        ,PoLineNum
        ,Address
        ,TaxCode
        ,TaxType
        ,OrigItem
        ,BackOrdr
        ,FreeTxt
        ,PickStatus
        ,PickOty
        ,PickIdNo
        ,TrnsCode
        ,VatAppld
        ,VatAppldFC
        ,VatAppldSC
        ,BaseQty
        ,BaseOpnQty
        ,VatDscntPr
        ,WtLiable
        ,DeferrTax
        ,EquVatPer
        ,EquVatSum
        ,EquVatSumF
        ,EquVatSumS
        ,LineVat
        ,LineVatlF
        ,LineVatS
        ,unitMsr
        ,NumPerMsr
        ,CEECFlag
        ,ToStock
        ,ToDiff
        ,ExciseAmt
        ,TaxPerUnit
        ,TotInclTax
        ,CountryOrg
        ,StckDstSum
        ,ReleasQtty
        ,LineType
        ,TranType
        ,Text
        ,OwnerCode
        ,StockPrice
        ,ConsumeFCT
        ,LstByDsSum
        ,StckINMPr
        ,LstBINMPr
        ,StckDstFc
        ,StckDstSc
        ,LstByDsFc
        ,LstByDsSc
        ,StockSum
        ,StockSumFc
        ,StockSumSc
        ,StckSumApp
        ,StckAppFc
        ,StckAppSc
        ,ShipToCode
        ,ShipToDesc
        ,StckAppD
        ,StckAppDFC
        ,StckAppDSC
        ,BasePrice
        ,GTotal
        ,GTotalFC
        ,GTotalSC
        ,DistribExp
        ,DescOW
        ,DetailsOW
        ,GrossBase
        ,VatWoDpm
        ,VatWoDpmFc
        ,VatWoDpmSc
        ,CFOPCode
        ,CSTCode
        ,Usage
        ,TaxOnly
        ,WtCalced
        ,QtyToShip
        ,DelivrdQty
        ,OrderedQty
        ,CogsOcrCod
        ,CiOppLineN
        ,CogsAcct
        ,ChgAsmBoMW
        ,ActDelDate
        ,OcrCode2
        ,OcrCode3
        ,OcrCode4
        ,OcrCode5
        ,TaxDistSum
        ,TaxDistSFC
        ,TaxDistSSC
        ,PostTax
        ,Excisable
        ,AssblValue
        ,RG23APart1
        ,RG23APart2
        ,RG23CPart1
        ,RG23CPart2
        ,CogsOcrCo2
        ,CogsOcrCo3
        ,CogsOcrCo4
        ,CogsOcrCo5
        ,LnExcised
        ,LocCode
        ,StockValue
        ,GPTtlBasPr
        ,unitMsr2
        ,NumPerMsr2
        ,SpecPrice
        ,CSTfIPI
        ,CSTfPIS
        ,CSTfCOFINS
        ,ExLineNo
        ,isSrvCall
        ,PQTReqQty
        ,PQTReqDate
        ,PcDocType
        ,PcQuantity
        ,LinManClsd
        ,VatGrpSrc
        ,NoInvtryMv
        ,ActBaseEnt
        ,ActBaseLn
        ,ActBaseNum
        ,OpenRtnQty
        ,AgrNo
        ,AgrLnNum
        ,CredOrigin
        ,Surpluses
        ,DefBreak
        ,Shortages
        ,UomEntry
        ,UomEntry2
        ,UomCode
        ,UomCode2
        ,FromWhsCod
        ,NeedQty
        ,PartRetire
        ,RetireQty
        ,RetireAPC
        ,RetirAPCFC
        ,RetirAPCSC
        ,InvQty
        ,OpenInvQty
        ,EnSetCost
        ,RetCost
        ,Incoterms
        ,TransMod
        ,LineVendor
        ,DistribIS
        ,ISDistrb
        ,ISDistrbFC
        ,ISDistrbSC
        ,IsByPrdct
        ,ItemType
        ,PriceEdit
        ,PrntLnNum
        ,LinePoPrss
        ,FreeChrgBP
        ,TaxRelev
        ,LegalText
        ,ThirdParty
        ,LicTradNum
        ,InvQtyOnly
        ,UnencReasn
        ,ShipFromCo
        ,ShipFromDe
        ,FisrtBin
        ,AllocBinC
        ,ExpType
        ,ExpUUID
        ,ExpOpType
        ,DIOTNat
        ,MYFtype
        ,GPBefDisc
        ,ReturnRsn
        ,ReturnAct
        ,StgSeqNum
        ,StgEntry
        ,StgDesc
        ,ItmTaxType
        ,SacEntry
        ,NCMCode
        ,HsnEntry
        ,OriBAbsEnt
        ,OriBLinNum
        ,OriBDocTyp
        ,IsPrscGood
        ,IsCstmAct
        ,EncryptIV
        ,ExtTaxRate
        ,ExtTaxSum
        ,TaxAmtSrc
        ,ExtTaxSumF
        ,ExtTaxSumS
        ,StdItemId
        ,CommClass
        ,VatExEntry
        ,VatExLN
        ,NatOfTrans
        ,ISDtCryImp
        ,ISDtRgnImp
        ,ISOrCryExp
        ,ISOrRgnExp
        ,NVECode
        ,PoNum
        ,PoItmNum
        ,IndEscala
        ,CESTCode
        ,CtrSealQty
        ,CNJPMan
        ,UFFiscBene
        ,CUSplit
        ,LegalTIMD
        ,LegalTTCA
        ,LegalTW
        ,LegalTCD
        ,RevCharge
        ,ListNum
        ,RecogAmt
        ,RecogAmtSC
        ,RecogAmtFC
        ,RecogVatGr
        ,RecogVatPr
        ,NonDdAmt
        ,NonDdAmtSC
        ,NonDdAmtFC
        ,PPTaxExRe
        ,PlPaWght
        ,CUP
        ,CIG
        ,U_QuantitySale
        ,U_UnPriSale
        ,U_BatchNumP
        ,U_Length
        ,U_Width
        ,U_BatchSelected
    )
    SELECT
         DocEntry
        ,LineNum
        ,TargetType
        ,TrgetEntry
        ,BaseRef
        ,BaseType
        ,BaseEntry
        ,BaseLine
        ,LineStatus
        ,ItemCode
        ,Dscription
        ,Quantity
        ,ShipDate
        ,OpenQty
        ,Price
        ,Currency
        ,Rate
        ,DiscPrcnt
        ,LineTotal
        ,TotalFrgn
        ,OpenSum
        ,OpenSumFC
        ,VendorNum
        ,SerialNum
        ,WhsCode
        ,SlpCode
        ,Commission
        ,TreeType
        ,AcctCode
        ,TaxStatus
        ,GrossBuyPr
        ,PriceBefDi
        ,DocDate
        ,Flags
        ,OpenCreQty
        ,UseBaseUn
        ,SubCatNum
        ,BaseCard
        ,TotalSumSy
        ,OpenSumSys
        ,InvntSttus
        ,OcrCode
        ,Project
        ,CodeBars
        ,VatPrcnt
        ,VatGroup
        ,PriceAfVAT
        ,Height1
        ,Hght1Unit
        ,Height2
        ,Hght2Unit
        ,Width1
        ,Wdth1Unit
        ,Width2
        ,Wdth2Unit
        ,Length1
        ,Len1Unit
        ,length2
        ,Len2Unit
        ,Volume
        ,VolUnit
        ,Weight1
        ,Wght1Unit
        ,Weight2
        ,Wght2Unit
        ,Factor1
        ,Factor2
        ,Factor3
        ,Factor4
        ,PackQty
        ,UpdInvntry
        ,BaseDocNum
        ,BaseAtCard
        ,SWW
        ,VatSum
        ,VatSumFrgn
        ,VatSumSy
        ,FinncPriod
        ,ObjType
        ,LogInstanc
        ,BlockNum
        ,ImportLog
        ,DedVatSum
        ,DedVatSumF
        ,DedVatSumS
        ,IsAqcuistn
        ,DistribSum
        ,DstrbSumFC
        ,DstrbSumSC
        ,GrssProfit
        ,GrssProfSC
        ,GrssProfFC
        ,VisOrder
        ,INMPrice
        ,PoTrgNum
        ,PoTrgEntry
        ,DropShip
        ,PoLineNum
        ,Address
        ,TaxCode
        ,TaxType
        ,OrigItem
        ,BackOrdr
        ,FreeTxt
        ,PickStatus
        ,PickOty
        ,PickIdNo
        ,TrnsCode
        ,VatAppld
        ,VatAppldFC
        ,VatAppldSC
        ,BaseQty
        ,BaseOpnQty
        ,VatDscntPr
        ,WtLiable
        ,DeferrTax
        ,EquVatPer
        ,EquVatSum
        ,EquVatSumF
        ,EquVatSumS
        ,LineVat
        ,LineVatlF
        ,LineVatS
        ,unitMsr
        ,NumPerMsr
        ,CEECFlag
        ,ToStock
        ,ToDiff
        ,ExciseAmt
        ,TaxPerUnit
        ,TotInclTax
        ,CountryOrg
        ,StckDstSum
        ,ReleasQtty
        ,LineType
        ,TranType
        ,Text
        ,OwnerCode
        ,StockPrice
        ,ConsumeFCT
        ,LstByDsSum
        ,StckINMPr
        ,LstBINMPr
        ,StckDstFc
        ,StckDstSc
        ,LstByDsFc
        ,LstByDsSc
        ,StockSum
        ,StockSumFc
        ,StockSumSc
        ,StckSumApp
        ,StckAppFc
        ,StckAppSc
        ,ShipToCode
        ,ShipToDesc
        ,StckAppD
        ,StckAppDFC
        ,StckAppDSC
        ,BasePrice
        ,GTotal
        ,GTotalFC
        ,GTotalSC
        ,DistribExp
        ,DescOW
        ,DetailsOW
        ,GrossBase
        ,VatWoDpm
        ,VatWoDpmFc
        ,VatWoDpmSc
        ,CFOPCode
        ,CSTCode
        ,Usage
        ,TaxOnly
        ,WtCalced
        ,QtyToShip
        ,DelivrdQty
        ,OrderedQty
        ,CogsOcrCod
        ,CiOppLineN
        ,CogsAcct
        ,ChgAsmBoMW
        ,ActDelDate
        ,OcrCode2
        ,OcrCode3
        ,OcrCode4
        ,OcrCode5
        ,TaxDistSum
        ,TaxDistSFC
        ,TaxDistSSC
        ,PostTax
        ,Excisable
        ,AssblValue
        ,RG23APart1
        ,RG23APart2
        ,RG23CPart1
        ,RG23CPart2
        ,CogsOcrCo2
        ,CogsOcrCo3
        ,CogsOcrCo4
        ,CogsOcrCo5
        ,LnExcised
        ,LocCode
        ,StockValue
        ,GPTtlBasPr
        ,unitMsr2
        ,NumPerMsr2
        ,SpecPrice
        ,CSTfIPI
        ,CSTfPIS
        ,CSTfCOFINS
        ,ExLineNo
        ,isSrvCall
        ,PQTReqQty
        ,PQTReqDate
        ,PcDocType
        ,PcQuantity
        ,LinManClsd
        ,VatGrpSrc
        ,NoInvtryMv
        ,ActBaseEnt
        ,ActBaseLn
        ,ActBaseNum
        ,OpenRtnQty
        ,AgrNo
        ,AgrLnNum
        ,CredOrigin
        ,Surpluses
        ,DefBreak
        ,Shortages
        ,UomEntry
        ,UomEntry2
        ,UomCode
        ,UomCode2
        ,FromWhsCod
        ,NeedQty
        ,PartRetire
        ,RetireQty
        ,RetireAPC
        ,RetirAPCFC
        ,RetirAPCSC
        ,InvQty
        ,OpenInvQty
        ,EnSetCost
        ,RetCost
        ,Incoterms
        ,TransMod
        ,LineVendor
        ,DistribIS
        ,ISDistrb
        ,ISDistrbFC
        ,ISDistrbSC
        ,IsByPrdct
        ,ItemType
        ,PriceEdit
        ,PrntLnNum
        ,LinePoPrss
        ,FreeChrgBP
        ,TaxRelev
        ,LegalText
        ,ThirdParty
        ,LicTradNum
        ,InvQtyOnly
        ,UnencReasn
        ,ShipFromCo
        ,ShipFromDe
        ,FisrtBin
        ,AllocBinC
        ,ExpType
        ,ExpUUID
        ,ExpOpType
        ,DIOTNat
        ,MYFtype
        ,GPBefDisc
        ,ReturnRsn
        ,ReturnAct
        ,StgSeqNum
        ,StgEntry
        ,StgDesc
        ,ItmTaxType
        ,SacEntry
        ,NCMCode
        ,HsnEntry
        ,OriBAbsEnt
        ,OriBLinNum
        ,OriBDocTyp
        ,IsPrscGood
        ,IsCstmAct
        ,EncryptIV
        ,ExtTaxRate
        ,ExtTaxSum
        ,TaxAmtSrc
        ,ExtTaxSumF
        ,ExtTaxSumS
        ,StdItemId
        ,CommClass
        ,VatExEntry
        ,VatExLN
        ,NatOfTrans
        ,ISDtCryImp
        ,ISDtRgnImp
        ,ISOrCryExp
        ,ISOrRgnExp
        ,NVECode
        ,PoNum
        ,PoItmNum
        ,IndEscala
        ,CESTCode
        ,CtrSealQty
        ,CNJPMan
        ,UFFiscBene
        ,CUSplit
        ,LegalTIMD
        ,LegalTTCA
        ,LegalTW
        ,LegalTCD
        ,RevCharge
        ,ListNum
        ,RecogAmt
        ,RecogAmtSC
        ,RecogAmtFC
        ,RecogVatGr
        ,RecogVatPr
        ,NonDdAmt
        ,NonDdAmtSC
        ,NonDdAmtFC
        ,PPTaxExRe
        ,PlPaWght
        ,CUP
        ,CIG
        ,U_QuantitySale
        ,U_UnPriSale
        ,U_BatchNumP
        ,U_Length
        ,U_Width
        ,U_BatchSelected
    FROM INV1_RN
    WHERE rn = 1;

END;
